### ISSUE TITLE
Refactor request: remove those .d.ts files maybe

### ISSUE THREAD

**Issue by maifeeulasad** [KhaledMowafy/moffbar#1]
Hello

I saw your repository and it's really amazing. But I have a question regarding these `.d.ts` files, are they really required? Cause you have written your project in 100% typescript.

Can we refactor them, and move them as part of the `.ts` files? Would like to hear your thoughts on this.

**Comment by KhaledMowafy** [comment]
Hello,

Thank you for your interest in the repository and for your kind words!

Regarding your question about the .d.ts files, as of my understanding, these are TypeScript declaration files that contain type information about a program. They are a key part of TypeScript's type system and are used to describe the shape of an object, allowing for type checking and IntelliSense in editors without having to have the actual implementation present.
Even though the project is written in 100% TypeScript, .d.ts files are still very useful, especially for the following reasons:

1. Library Consumers: whether a JS or a TS project
2. Code Separation

Moving the .d.ts files into the .ts files is possible and could be done if it makes sense for the project. However, it would mean that the type definitions will be spread across the codebase, which might make maintenance more challenging in the long run.

Again I would love to discuss this further with you and if there is a better practice or some better trick out there that I have missed please share it with me I would love to pick it up.

**Comment by maifeeulasad** [comment]
Thanks for breaking down the `.d.ts` file role—it really clarifies things! Totally get their importance for library users and keeping code neat.

If you need any support regarding development of this repo or others, please let me know.

**Comment by KhaledMowafy** [comment]
@maifeeulasad sure lets set up a meeting maybe discuss doing projects together if you are interested.
